export const dummyProducts = [
  {
    id: 1,
    title: "Wireless Bluetooth Headphones",
    description: "Premium sound quality with noise cancellation technology",
    price: 129.99,
    image: "https://picsum.photos/400/225?random=1",
    availableQty: 15,
  },
  {
    id: 2,
    title: "Smartphone Stand Holder",
    description: "Adjustable ergonomic desktop stand for phones and tablets",
    price: 24.99,
    image: "https://picsum.photos/400/225?random=2",
    availableQty: 42,
  },
  {
    id: 3,
    title: "Smart Fitness Tracker",
    description: "Track your health metrics with this waterproof smart device",
    price: 89.99,
    image: "https://picsum.photos/400/225?random=3",
    availableQty: 8,
  },
  {
    id: 4,
    title: "Mechanical Keyboard",
    description: "RGB backlit mechanical gaming keyboard with custom switches",
    price: 159.99,
    image: "https://picsum.photos/400/225?random=4",
    availableQty: 23,
  },
  {
    id: 5,
    title: "Portable Power Bank",
    description: "20000mAh fast charging power bank with dual USB ports",
    price: 49.99,
    image: "https://picsum.photos/400/225?random=5",
    availableQty: 31,
  },
  {
    id: 6,
    title: "Wireless Charging Pad",
    description: "Fast wireless charging for all Qi-enabled devices",
    price: 29.99,
    image: "https://picsum.photos/400/225?random=6",
    availableQty: 19,
  },
  {
    id: 7,
    title: "Smart LED Desk Lamp",
    description:
      "Adjustable brightness and color temperature with touch controls",
    price: 44.99,
    image: "https://picsum.photos/400/225?random=7",
    availableQty: 12,
  },
  {
    id: 8,
    title: "Premium Backpack",
    description: "Water-resistant laptop backpack with USB charging port",
    price: 79.99,
    image: "https://picsum.photos/400/225?random=8",
    availableQty: 17,
  },
  {
    id: 9,
    title: "Wireless Mouse",
    description: "Ergonomic design with adjustable DPI and silent clicking",
    price: 34.99,
    image: "https://picsum.photos/400/225?random=9",
    availableQty: 27,
  },
];
