export const dummyProducts = [
  {
    id: 1,
    title: "Wireless Bluetooth Headphones",
    description: "Premium sound quality with noise cancellation technology",
    price: 129.99,
    image: "https://i.postimg.cc/0QGcrwWN/headphones.jpg",
    availableQty: 15,
  },
  {
    id: 2,
    title: "Smartphone Stand Holder",
    description: "Adjustable ergonomic desktop stand for phones and tablets",
    price: 24.99,
    image: "https://i.postimg.cc/50mSfMyY/stand-holder.jpg",
    availableQty: 42,
  },
  {
    id: 3,
    title: "Smart Fitness Tracker",
    description: "Track your health metrics with this waterproof smart device",
    price: 89.99,
    image: "https://i.postimg.cc/W3c52n7K/fitness-tracker.jpg",
    availableQty: 8,
  },
  {
    id: 4,
    title: "Mechanical Keyboard",
    description: "RGB backlit mechanical gaming keyboard with custom switches",
    price: 159.99,
    image: "https://i.postimg.cc/NFpDkwwq/keyboard.jpg",
    availableQty: 23,
  },
  {
    id: 5,
    title: "Portable Power Bank",
    description: "20000mAh fast charging power bank with dual USB ports",
    price: 49.99,
    image: "https://i.postimg.cc/wjt2LPfZ/power-bank.jpg",
    availableQty: 31,
  },
  {
    id: 6,
    title: "Wireless Charging Pad",
    description: "Fast wireless charging for all Qi-enabled devices",
    price: 29.99,
    image: "https://i.postimg.cc/Jzt6KtnT/charging-pad.jpg",
    availableQty: 19,
  },
  {
    id: 7,
    title: "Smart LED Desk Lamp",
    description:
      "Adjustable brightness and color temperature with touch controls",
    price: 44.99,
    image: "https://i.postimg.cc/fb9HnFYm/desk-lamp.jpg",
    availableQty: 12,
  },
  {
    id: 8,
    title: "Premium Backpack",
    description: "Water-resistant laptop backpack with USB charging port",
    price: 79.99,
    image: "https://i.postimg.cc/c4x5gFNG/backpack.jpg",
    availableQty: 17,
  },
  {
    id: 9,
    title: "Wireless Mouse",
    description: "Ergonomic design with adjustable DPI and silent clicking",
    price: 34.99,
    image: "https://i.postimg.cc/J7qpLjH6/mouse.jpg",
    availableQty: 27,
  },
];
